type User {
  id: ID!
  email: String!
  token: String!
  events: [Event] @relation
  accounts: [Account] @relation
  created: Time!
}

type Event {
  id: ID!
  account: Account!
  title: String!
  locations: [String]
  created: Time!
  user: User!
}

type Account {
  id: ID!
  email: String!
  apikey: String!
  user: User!
  events: [Event] @relation
}
